//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praxis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraNavegacion
    {
        public int IdBitacora { get; set; }
        public string IdUsuario { get; set; }
        public int IdPantalla { get; set; }
        public int IdEvento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string IdRegistro { get; set; }
        public string Campo { get; set; }
        public string ValorActual { get; set; }
        public string ValorNuevo { get; set; }
        public string Parametro { get; set; }
        public byte[] Acuse { get; set; }
        public Nullable<System.Guid> Folio { get; set; }
        public string Host { get; set; }
    }
}
