//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praxis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public int IdHistoriaClinica { get; set; }
        public System.Guid IdUsuario { get; set; }
        public int IdSexo { get; set; }
        public int IdEstadoCivil { get; set; }
        public int IdReligion { get; set; }
        public int IdTipoSangre { get; set; }
        public int IdEscolaridad { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public string LugarNacimiento { get; set; }
        public string LugarResidencia { get; set; }
        public string Ocupacion { get; set; }
        public string NumeroSeguridadSocial { get; set; }
        public string PolizaSeguro { get; set; }
        public string AbueloPaterno { get; set; }
        public string AbuelaPaterno { get; set; }
        public string AbueloMaterno { get; set; }
        public string AbuelaMaterno { get; set; }
        public string Padre { get; set; }
        public string Madre { get; set; }
        public string Hermano { get; set; }
        public string Hijo { get; set; }
        public string Vivienda { get; set; }
        public string Zoonosis { get; set; }
        public string Habitos { get; set; }
        public string IngestaLiquido { get; set; }
        public string Higiene { get; set; }
        public string Inmunizacion { get; set; }
        public string LenguaIndigena { get; set; }
        public string Combe { get; set; }
        public string ViajeReciente { get; set; }
        public string ExposicionBiomasa { get; set; }
        public string CronicoDegenerativo { get; set; }
        public string Quirurjicos { get; set; }
        public string Hospitalizacion { get; set; }
        public string Infectocontagioso { get; set; }
        public string Traumatico { get; set; }
        public string Toxicomania { get; set; }
        public string Transfusional { get; set; }
        public string Alergia { get; set; }
        public string ConsumoTabaco { get; set; }
        public string ConsumoAlcohol { get; set; }
        public string InicioVidaSexual { get; set; }
        public string NumeroParejaSexual { get; set; }
        public string Parejas { get; set; }
        public string CantidadHijo { get; set; }
        public string MetodoPlanificacion { get; set; }
        public string InfeccionSexual { get; set; }
        public string Menarca { get; set; }
        public string Telarca { get; set; }
        public string Gesta { get; set; }
        public string Parto { get; set; }
        public string Aborto { get; set; }
        public string Cesarea { get; set; }
        public string Papanicolau { get; set; }
        public string Mastografia { get; set; }
    
        public virtual CatSexo CatSexo { get; set; }
        public virtual CatTipoSangre CatTipoSangre { get; set; }
        public virtual CatUsuario CatUsuario { get; set; }
        public virtual CatReligion CatReligion { get; set; }
        public virtual CatEscolaridad CatEscolaridad { get; set; }
        public virtual CatEstadoCivil CatEstadoCivil { get; set; }
    }
}
