//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praxis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloxUsuario
    {
        public int IdPantalla { get; set; }
        public string IdUsuario { get; set; }
        public bool Aprobar { get; set; }
        public bool Escritura { get; set; }
        public bool Lectura { get; set; }
    }
}
