CREATE TABLE [dbo].[HistoriaClinica] (
    [IdHistoriaClinica]     INT              IDENTITY (1, 1) NOT NULL,
    [IdUsuario]             UNIQUEIDENTIFIER NOT NULL,
    [IdSexo]                INT              NOT NULL,
    [IdEstadoCivil]         INT              NOT NULL,
    [IdReligion]            INT              NOT NULL,
    [IdTipoSangre]          INT              NOT NULL,
    [IdEscolaridad]         INT              NOT NULL,
    [Activo]                BIT              NOT NULL,
    [FechaNacimiento]       DATETIME         NOT NULL,
    [FechaActualizacion]    DATETIME         NOT NULL,
    [LugarNacimiento]       NVARCHAR (300)   NOT NULL,
    [LugarResidencia]       NVARCHAR (300)   NOT NULL,
    [Ocupacion]             NVARCHAR (100)   NOT NULL,
    [NumeroSeguridadSocial] NVARCHAR (50)    NOT NULL,
    [PolizaSeguro]          NVARCHAR (50)    NULL,
    [AbueloPaterno]         NVARCHAR (300)   NULL,
    [AbuelaPaterno]         NVARCHAR (300)   NULL,
    [AbueloMaterno]         NVARCHAR (300)   NULL,
    [AbuelaMaterno]         NVARCHAR (300)   NULL,
    [Padre]                 NVARCHAR (300)   NULL,
    [Madre]                 NVARCHAR (300)   NULL,
    [Hermano]               NVARCHAR (300)   NULL,
    [Hijo]                  NVARCHAR (300)   NULL,
    [Vivienda]              NVARCHAR (500)   NULL,
    [Zoonosis]              NVARCHAR (300)   NULL,
    [Habitos]               NVARCHAR (500)   NULL,
    [IngestaLiquido]        NVARCHAR (300)   NULL,
    [Higiene]               NVARCHAR (300)   NULL,
    [Inmunizacion]          NVARCHAR (300)   NULL,
    [LenguaIndigena]        NVARCHAR (50)    NULL,
    [Combe]                 NVARCHAR (300)   NULL,
    [ViajeReciente]         NVARCHAR (300)   NOT NULL,
    [ExposicionBiomasa]     NVARCHAR (300)   NOT NULL,
    [CronicoDegenerativo]   NVARCHAR (500)   NOT NULL,
    [Quirurjicos]           NVARCHAR (500)   NOT NULL,
    [Hospitalizacion]       NVARCHAR (500)   NOT NULL,
    [Infectocontagioso]     NVARCHAR (500)   NOT NULL,
    [Traumatico]            NVARCHAR (500)   NOT NULL,
    [Toxicomania]           NVARCHAR (500)   NOT NULL,
    [Transfusional]         NVARCHAR (500)   NOT NULL,
    [Alergia]               NVARCHAR (500)   NOT NULL,
    [ConsumoTabaco]         NVARCHAR (300)   NOT NULL,
    [ConsumoAlcohol]        NVARCHAR (300)   NOT NULL,
    [InicioVidaSexual]      NVARCHAR (300)   NULL,
    [NumeroParejaSexual]    NVARCHAR (300)   NULL,
    [Parejas]               NVARCHAR (300)   NULL,
    [CantidadHijo]          NVARCHAR (300)   NULL,
    [MetodoPlanificacion]   NVARCHAR (300)   NOT NULL,
    [InfeccionSexual]       NVARCHAR (300)   NOT NULL,
    [Menarca]               NVARCHAR (300)   NULL,
    [Telarca]               NVARCHAR (300)   NULL,
    [Gesta]                 NVARCHAR (300)   NULL,
    [Parto]                 NVARCHAR (300)   NULL,
    [Aborto]                NVARCHAR (300)   NULL,
    [Cesarea]               NVARCHAR (300)   NULL,
    [Papanicolau]           NVARCHAR (300)   NULL,
    [Mastografia]           NVARCHAR (300)   NULL,
    CONSTRAINT [PK_HistoriaClinica] PRIMARY KEY CLUSTERED ([IdHistoriaClinica] ASC),
    CONSTRAINT [FK_HistoriaClinica_CatEscolaridad] FOREIGN KEY ([IdEscolaridad]) REFERENCES [dbo].[CatEscolaridad] ([IdEscolaridad]),
    CONSTRAINT [FK_HistoriaClinica_CatEstadoCivil] FOREIGN KEY ([IdEstadoCivil]) REFERENCES [dbo].[CatEstadoCivil] ([IdEstadoCivil]),
    CONSTRAINT [FK_HistoriaClinica_CatReligion] FOREIGN KEY ([IdReligion]) REFERENCES [dbo].[CatReligion] ([IdReligion]),
    CONSTRAINT [FK_HistoriaClinica_CatSexo] FOREIGN KEY ([IdSexo]) REFERENCES [dbo].[CatSexo] ([IdSexo]),
    CONSTRAINT [FK_HistoriaClinica_CatTipoSangre] FOREIGN KEY ([IdTipoSangre]) REFERENCES [dbo].[CatTipoSangre] ([IdTipoSangre]),
    CONSTRAINT [FK_HistoriaClinica_CatUsuario] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[CatUsuario] ([IdUsuario])
);







